# Generated by Django 4.2.1 on 2023-06-27 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pet_shop', '0005_orderedproducts_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderedproducts',
            name='products',
        ),
        migrations.AddField(
            model_name='orderedproducts',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pet_shop.product'),
        ),
    ]
