# Generated by Django 4.2.1 on 2023-06-27 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_shop', '0006_remove_orderedproducts_products_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cart_products',
            field=models.ManyToManyField(related_name='products_from_cart', to='pet_shop.orderedproducts'),
        ),
    ]
