# Generated by Django 4.2.1 on 2023-06-28 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_shop', '0008_alter_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedproducts',
            name='size',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
