# Generated by Django 4.2.1 on 2023-06-28 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet_shop', '0009_alter_orderedproducts_size'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
