# Generated by Django 4.2.1 on 2023-06-28 00:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pet_shop', '0010_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('postcode', models.CharField(max_length=255)),
                ('payment_type', models.CharField(choices=[('Credit Card', 'Credit Card'), ('Delivery', 'Delivery')], max_length=255)),
                ('date', models.DateTimeField(auto_now=True)),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
                ('cart_products', models.ManyToManyField(related_name='products_from_cart', to='pet_shop.orderedproducts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
