# Generated by Django 4.2.1 on 2023-06-28 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pet_shop', '0012_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='superuser',
            name='userprofile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pet_shop.userprofile'),
        ),
    ]
