# Generated by Django 4.2.1 on 2023-06-28 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_shop', '0016_remove_cart_userprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproduct',
            name='session_key',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
