# Generated by Django 4.2.1 on 2023-06-28 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_shop', '0018_alter_cartproduct_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='session_key',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
