# Generated by Django 4.2.1 on 2023-06-28 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet_shop', '0020_alter_cartproduct_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='session_key',
        ),
        migrations.RemoveField(
            model_name='cartproduct',
            name='session_key',
        ),
    ]
