# Generated by Django 4.2.1 on 2023-06-28 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_shop', '0021_remove_cart_session_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='processed',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
