# Generated by Django 4.2.1 on 2023-06-28 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_shop', '0022_order_processed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
