# Generated by Django 4.2.1 on 2023-06-28 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet_shop', '0023_alter_order_processed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='processed',
        ),
    ]
